USE [master]
GO

/****** Object:  Database [CRUDDB]    Script Date: 24/01/2022 14:52:13 ******/
CREATE DATABASE [CRUDDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CRUDDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\CRUDDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CRUDDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\CRUDDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CRUDDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CRUDDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CRUDDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CRUDDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CRUDDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CRUDDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CRUDDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [CRUDDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CRUDDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CRUDDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CRUDDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CRUDDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CRUDDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CRUDDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CRUDDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CRUDDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [CRUDDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CRUDDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CRUDDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CRUDDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CRUDDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CRUDDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CRUDDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CRUDDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CRUDDB] SET  MULTI_USER 
GO

ALTER DATABASE [CRUDDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CRUDDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CRUDDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CRUDDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CRUDDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CRUDDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CRUDDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [CRUDDB] SET  READ_WRITE 
GO

